apiVersion: v1
kind: Service
metadata:
  name: fabric-service
  labels:
    app: fabric
    {{- range $label := .Values.labelsList }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: 
  ports:
  - port: {{ .Values.listening_port }}
    targetPort: {{ .Values.listening_port }}
    protocol: TCP
    name: fabric-port
  selector:
    app: fabric