{{- if .Values.ingress.tlsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fabric-private-ingress-ssl
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/tls
stringData:
  tls.key: {{ .Values.ingress.tlsSecret.key }}
  tls.crt: {{ .Values.ingress.tlsSecret.crt }}
{{- end }}