apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: k2view-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k2view-agent
  template:
    metadata:
      labels:
        app: k2view-agent
    spec:
      {{- if .Values.image.addDockerRegistry }}
      imagePullSecrets:
        -name: {{ .Values.image.dockerRegistrySecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.url }}
          imagePullPolicy: IfNotPresent
          env:
            {{- range $key, $value :=  .Values.secrets }}
            {{- if not (empty $value) }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: agent-config-secrets
                  key: {{ $key }}
            {{- end }}
            {{- end }}
            {{- if .Values.serviceAccount.create }}
            - name: kubeToken
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.serviceAccount.name }}
                  key: token
            {{- end }}
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - ps aux | grep K2v-Agent | grep -v grep
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
