{{- $namespace := default dict .Values.namespace }}
{{- $namespace_name := default .Release.Name $namespace.name }}

{{- if $namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace_name }}
  labels:
    app: k2view-agent
{{- end }}
