
{{- $namespace := default dict .Values.namespace }}
{{- $namespace_name := default .Release.Name $namespace.name }}
{{- $image := default dict .Values.image }}
{{- $repoSecret := default dict .Values.repoSecret }}

{{- if $repoSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repoSecret.name }}
  namespace: {{ $namespace_name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $repoSecret.dockerRegistry | toJson | b64enc }}
{{- end }}
