{{- $namespace := default dict .Values.namespace }}
{{- $namespace_name := default .Release.Name $namespace.name }}
{{- $serviceAccount := default dict .Values.serviceAccount }}

{{- if $serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $namespace_name }}-sa
  namespace: {{ $namespace_name }}
  {{ if eq $serviceAccount.provider "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ $serviceAccount.arn }}"
  {{ else if eq $serviceAccount.provider "gcp" }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ $serviceAccount.gcp_service_account_name }}@{{ $serviceAccount.project_id }}.iam.gserviceaccount.com"
  {{ else if eq $serviceAccount.provider "azure" }}
  annotations:
    azure.workload.identity/client-id: "{{ $serviceAccount.azure_workload_identity_client_id }}"
  {{ end }}
  labels:
    {{- include "K2ViewAgent.labels" . | nindent 4 }}
{{- end }}
