{{ if .Values.scaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    labels:
        app: fabric
        {{- range $label := .Values.labels }}
        {{ $label.name }}: {{ $label.value }}
        {{- end }}
    name: fabric-hpa
    namespace: {{ .Values.namespace.name }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: {{ .Values.deploy.type }}
        name: fabric-deployment
    minReplicas: {{ .Values.scaling.minReplicas }}
    maxReplicas: {{ .Values.scaling.maxReplicas }}
    targetCPUUtilizationPercentage: {{ .Values.scaling.targetCPU }}
{{ end }}