{{ $namespace := default dict .Values.namespace }}
{{ $scaling := default dict .Values.scaling }}
{{ $global := default dict .Values.global }}
{{ $labels := $global.labels | default (list) }}
{{ $global_annotations := $global.annotations | default (list) }}
{{ $scaling_annotations := $scaling.annotations | default (list) }}

{{ if $scaling.enabled | default false }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: fabric-hpa
    namespace: {{ default .Release.Name $namespace.name }}
    labels:
        app: fabric
        {{- range $label := $labels }}
        {{ $label.name }}: {{ $label.value }}
        {{- end }}
    {{- if or $global_annotations $scaling_annotations }}
    annotations:
      {{- range $annotation := $global_annotations }}
      {{ $annotation.key }}: {{ $annotation.value | quote }}
      {{- end }}
      {{- range $annotation := $scaling_annotations }}
      {{ $annotation.key }}: {{ $annotation.value | quote }}
      {{- end }}
    {{- end }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: {{ $scaling.targetKind | default "StatefulSet" }}
        name: {{ $scaling.targetName | default "fabric-stateful-sets" }}
    minReplicas: {{ $scaling.minReplicas | default 1 }}
    maxReplicas: {{ $scaling.maxReplicas | default 1 }}
    targetCPUUtilizationPercentage: {{ $scaling.targetCPU | default 90 }}
{{ end }}
