{{ $namespace := default dict .Values.namespace }}
{{ $container := default dict .Values.container }}
{{ $repoSecret := default dict $container.image.repoSecret }}
{{ $global := default dict .Values.global }}
{{ $global_labels := default (list) $global.labels }}
{{ $labels := default (list) .Values.labels }}
{{ $global_annotations := default (list) $global.annotations }}
{{ $annotations := default (list) .Values.annotations }}
{{ $secrets := default dict .Values.secrets }}
{{ $secret_annotations := default (list) $secrets.annotations }}

{{- if $repoSecret.enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repoSecret.name | default "registry-secret" }}
  namespace: {{ default .Release.Name $namespace.name }}
  labels:
    app: fabric
    {{- range $label := $labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $global_labels }}
    {{ $label.key }}: {{ $label.value }}
    {{- end }}
  {{- if or $global_annotations $secret_annotations $annotations }}
  annotations:
    {{- range $annotation := $global_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $secret_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $repoSecret.dockerRegistry | toJson | b64enc }}
{{- end }}
