{{ $namespace := default dict .Values.namespace }}
{{ $container := default dict .Values.container }}
{{ $repoSecret := default dict $container.image.repoSecret }}

{{- if $repoSecret.enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repoSecret.name | default "registry-secret" }}
  namespace: {{ default .Release.Name $namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $repoSecret.dockerRegistry | toJson | b64enc }}
{{- end }}
