{{ $namespace := default dict .Values.namespace }}
{{ $global := default dict .Values.global }}
{{ $global_labels := default (list) $global.labels }}
{{ $labels := default (list) .Values.labels }}
{{ $global_annotations := default (list) $global.annotations }}
{{ $annotations := default (list) .Values.annotations }}
{{ $secretsList := default dict .Values.secretsList }}
{{ $initSecretsList := default dict .Values.initSecretsList }}
{{ $secrets := default dict .Values.secrets }}
{{ $secret_annotations := default (list) $secrets.annotations }}

{{- range $secretsList }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Name $namespace.name }}
  labels:
    app: fabric
    {{- range $label := $labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $global_labels }}
    {{ $label.key }}: {{ $label.value }}
    {{- end }}
  {{- if or $global_annotations $secret_annotations $annotations }}
  annotations:
    {{- range $annotation := $global_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $secret_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := .data }}
{{- if $value }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- end }}
{{- range $initSecretsList }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Name $namespace.name }}
  labels:
    app: fabric
    {{- range $label := $labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $global_labels }}
    {{ $label.key }}: {{ $label.value }}
    {{- end }}
  {{- if or $global_annotations $secret_annotations $annotations }}
  annotations:
    {{- range $annotation := $global_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $secret_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := .data }}
{{- if $value }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- end }}
