{{ $namespace := default dict .Values.namespace }}
{{ $secretsList := default dict .Values.secretsList }}
{{ $initSecretsList := default dict .Values.initSecretsList }}

{{- range $secretsList }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Name $namespace.name }}
type: Opaque
data:
{{- range $key, $value := .data }}
{{- if $value }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- end }}
{{- range $initSecretsList }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Name $namespace.name }}
type: Opaque
data:
{{- range $key, $value := .data }}
{{- if $value }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- end }}
