{{ $namespace := default dict .Values.namespace }}
{{ $global := default dict .Values.global }}
{{ $global_labels := default (list) $global.labels }}
{{ $global_annotations := default (list) $global.annotations }}
{{ $annotations := default (list) .Values.annotations }}
{{ $service := default dict .Values.service }}
{{ $resource_annotations := default (list) $service.annotations }}
{{ $labels := default (list) .Values.labels }}

apiVersion: v1
kind: Service
metadata:
  name: fabric-service
  namespace: {{ default .Release.Name $namespace.name }}
  labels:
    app: fabric
    {{- range $label := $labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $global_labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
  {{- if or $global_annotations $resource_annotations $annotations }}
  annotations:
    {{- range $annotation := $global_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $resource_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
  - port: {{ $service.listening_port | default 3213 }}
    targetPort: {{ $service.listening_port | default 3213 }}
    protocol: TCP
    name: fabric-port
  selector:
    app: fabric
