{{ $namespace := default dict .Values.namespace }}
{{ $global := default dict .Values.global }}
{{ $labels := $global.labels | default (list) }}
{{ $global_annotations := $global.annotations | default (list) }}
{{ $service := default dict .Values.service }}
{{ $resource_annotations := $service.annotations | default (list) }}

apiVersion: v1
kind: Service
metadata:
  name: fabric-service
  namespace: {{ default .Release.Name $namespace.name }}
  labels:
    app: fabric
    {{- range $label := $labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
  {{- if or $global_annotations $resource_annotations }}
  annotations:
    {{- range $annotation := $global_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $resource_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
  - port: {{ $service.listening_port | default 3213 }}
    targetPort: {{ $service.listening_port | default 3213 }}
    protocol: TCP
    name: fabric-port
  selector:
    app: fabric
