{{ $namespace := default dict .Values.namespace }}
{{ $ingress := default dict .Values.ingress }}
{{ $tlsSecret := default dict $ingress.tlsSecret }}

{{- if and $tlsSecret.enabled (or (and (ne (toString ($tlsSecret.key | default "")) "") (ne (toString ($tlsSecret.crt | default "")) "")) (and (ne (toString ($tlsSecret.key_b64 | default "")) "") (ne (toString ($tlsSecret.crt_b64 | default "")) ""))) }}
apiVersion: v1
kind: Secret
metadata:
  name: fabric-private-ingress-ssl
  namespace: {{ default .Release.Name $namespace.name }}
type: kubernetes.io/tls
data:
  {{- if and ($tlsSecret.key_b64 | default "") ($tlsSecret.crt_b64 | default "") }}
  tls.key: {{ $tlsSecret.key_b64 | default "" }}
  tls.crt: {{ $tlsSecret.crt_b64 | default "" }}
  {{- else if and ($tlsSecret.key | default "") ($tlsSecret.crt | default "") }}
  tls.key: {{ $tlsSecret.key | default "" | toString | b64enc }}
  tls.crt: {{ $tlsSecret.crt | default "" | toString | b64enc }}
  {{- end }}
{{- end }}
