{{ $namespace := default dict .Values.namespace }}
{{ $ingress := default dict .Values.ingress }}
{{ $tlsSecret := default dict $ingress.tlsSecret }}
{{ $global := default dict .Values.global }}
{{ $global_labels := default (list) $global.labels }}
{{ $labels := default (list) .Values.labels }}
{{ $global_annotations := default (list) $global.annotations }}
{{ $annotations := default (list) .Values.annotations }}
{{ $secrets := default dict .Values.secrets }}
{{ $secret_annotations := default (list) $secrets.annotations }}
{{- if and $tlsSecret.enabled (or (and (ne (toString ($tlsSecret.key | default "")) "") (ne (toString ($tlsSecret.crt | default "")) "")) (and (ne (toString ($tlsSecret.key_b64 | default "")) "") (ne (toString ($tlsSecret.crt_b64 | default "")) ""))) }}
apiVersion: v1
kind: Secret
metadata:
  name: fabric-private-ingress-ssl
  namespace: {{ default .Release.Name $namespace.name }}
  labels:
    app: fabric
    {{- range $label := $labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $global_labels }}
    {{ $label.key }}: {{ $label.value }}
    {{- end }}
  {{- if or $global_annotations $secret_annotations $annotations }}
  annotations:
    {{- range $annotation := $global_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $secret_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
  {{- end }}
type: kubernetes.io/tls
data:
  {{- if and ($tlsSecret.key_b64 | default "") ($tlsSecret.crt_b64 | default "") }}
  tls.key: {{ $tlsSecret.key_b64 | default "" }}
  tls.crt: {{ $tlsSecret.crt_b64 | default "" }}
  {{- else if and ($tlsSecret.key | default "") ($tlsSecret.crt | default "") }}
  tls.key: {{ $tlsSecret.key | default "" | toString | b64enc }}
  tls.crt: {{ $tlsSecret.crt | default "" | toString | b64enc }}
  {{- end }}
{{- end }}
