{{- if .Values.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "tls.secretName is required when tls.create=true" .Values.tls.secretName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "traefik-ingress-controller.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "tls.crt is required when tls.create=true" .Values.tls.crt | b64enc | quote }}
  tls.key: {{ required "tls.key is required when tls.create=true" .Values.tls.key | b64enc | quote }}
{{- end }}
