{{- if and .Values.domain .Values.errorPage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-error-pages
  namespace: {{ .Release.Namespace }}
data:
    default.conf: |
      server {
          listen 80;

          location / {
              error_page 404 =404 /404.html;
              return 404;
          }
          
          location = /404.html {
              proxy_pass {{ .Values.errorPage.cloudfront_url }};
          }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-errors
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-errors
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-errors
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      serviceAccountName: restricted-sa
      containers:
      - name: nginx-error-server
        image: {{ .Values.errorPage.image }}
        securityContext:
          allowPrivilegeEscalation: false
        # Mounting custom error page rules from configMap
        volumeMounts:
        - name: custom-error-pages
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
            limits:
              memory: 128Mi
              cpu: '0.2'
      # Mounting custom error page rules from configMap
      volumes:
      - name: custom-error-pages
        configMap:
          name: custom-error-pages
          items:
          - key: default.conf
            path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-errors-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - "*.{{ .Values.domain }}"
  rules:
  - host: "*.{{ .Values.domain }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-errors
            port:
              number: 80
{{- end }}
