{{- if and .Values.tlsSecret.key .Values.tlsSecret.cert }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: wildcard-certificate
  namespace: {{ .Release.Namespace }}
data:
  tls.key: "{{ .Files.Get .Values.tlsSecret.key | b64enc | default .Values.tlsSecret.key }}"
  tls.crt: "{{ .Files.Get .Values.tlsSecret.cert | b64enc | default .Values.tlsSecret.cert }}"
{{- end }}
