---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.sc_name }}
provisioner: efs.csi.aws.com
parameters:
  basePath: /dynamic_provisioning
  directoryPerms: {{ .Values.permissions | quote }}
  fileSystemId: {{ .Values.efs_id }}
  gidRangeEnd: {{ .Values.gidRangeEnd | quote }}
  gidRangeStart: {{ .Values.gidRangeStart | quote }}
  provisioningMode: efs-ap
  uid: {{ .Values.uid | quote }}