apiVersion: v1
entries:
  fabric-space:
  - apiVersion: v2
    appVersion: 1.2.5
    created: "2024-02-01T18:17:51.9978791+02:00"
    dependencies:
    - condition: cassandra.enabled
      name: cassandra
      repository: file://./charts/cassandra
      version: ~0.1.0-0
    - condition: fabric.enabled
      name: fabric
      repository: file://./charts/fabric
      version: ~0.1.0-0
    description: The following Helm Chart Deploys Fabric and Cassandra
    digest: ee1f300220e27d8a5fcf3abf183c1ed2e1c9fb62746278209813e573fd6a28e2
    name: fabric-space
    type: application
    urls:
    - https://github.com/k2view/blueprints/tree/fabric_cassandra/helm/fabric-space/fabric-space-0.1.0.tgz
    version: 0.1.0
generated: "2024-02-01T18:17:51.995786+02:00"
