cassandra:
  enabled: true
  namespace:
    create: true
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

  container:
    replicas: 1
    image:
      url: cassandra:4.1.5
      repoSecret:
        name: "registry-secret"
        enabled: false
    storage_path: "/var/lib/cassandra"
    
    resource_allocation:
      limits:
        memory: 4Gi
        cpu: '1'
      requests:
        memory: 2Gi
        cpu: '0.5'
    
    envList:
    - key: HEAP_NEWSIZE
      value: 128M
    - key: MAX_HEAP_SIZE
      value: 2G
    - key: CASSANDRA_DC
      value: DC1
    - key: CASSANDRA_ENDPOINT_SNITCH
      value: GossipingPropertyFileSnitch

  credentials:
    cassandra_username: cassandra
    cassandra_password: cassandra

  # Deploy network policy that allow ingress only from Fabric pod
  networkPolicy:
    enabled: false

  # Cassandra port
  listening_port: 9042

  storage:
    class: regional-pd
    alocated_amount: 10Gi

fabric:
  enabled: true
  namespace:
    create: false
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

  deploy:
    type: Deployment

  serviceAccount:
    create: true   # For new sa, creation of sa only in k8s side
    name: ""       # For existing sa, if create is true, name should be an empty string
    provider: ""   # aws|gcp
    arn: ""        # For AWS role
    # gcp_service_account_name: "" # For GCP sa
    project_id: "" # For GCP SA
    cluster_name: ""
      
  container:
    replicas: 1
    resource_allocation:
      limits:
        memory: 8Gi
        cpu: '2'
      requests:
        memory: 2Gi
        cpu: '0.5'
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 60
    
    # Fabric Image to be populated into Deployment
    image:
      url: ""
      repoSecret:
        enabled: false

  storage:
    pvc:
      enabled: true
    securityContext: true
    class: regional-pd
    alocated_amount: 10Gi

  # Wether if Fabric will scale up or not
  scaling:
    enabled: false

  # Deploy network policy that allow to fabric egress only to cassandra pod
  networkPolicy:
    ingress:
      enabled: false
    egress:
      enabled: false

  ingress:
    enabled: true
    class_name: "nginx"
    type: "nginx"
    port: 3213
    host: space-tenant.domain
    tlsSecret:
      enabled: false
      key_b64: ""
      crt_b64: ""
    custom_annotations:
      enabled: false

  # Each key in the data will be mounted as a file under mountPath
  mountSecret:
    name: config-secrets
    enabled: false # true for mount the secret on fabric pod, false for mount only on init container
    mountPath: /opt/apps/fabric/config-secrets
    data:
      config: |
        fabricdb|MDB_DEFAULT_CACHE_PATH|/opt/apps/fabric/pod_tmp/fdb_cache
        default_pubsub|TYPE|MEMORY
        common_area_pubsub|TYPE|MEMORY
        fabric|WEB_SESSION_EXPIRATION_TIME_OUT|540
        fabric|ENABLE_BROADWAY_DEBUG_SERVLET|true
        default_session|RECONNECT_MAX_DELAY_MS|1000
        fabric|ENABLE_DB_INTERFACE_PROXY|true
        fabric|WEBSERVER_FILTERS|[{\"class\":\"com.k2view.cdbms.ws.ProxyForward\",\"patterns\":[\"/studio/*\"],\"params\":{\"target\":\"http://localhost:3000\",\"isStaticTarget\":true}},{\"class\":\"com.k2view.cdbms.ws.ProxyForward\",\"patterns\":[\"/socket.io/*\"],\"params\":{\"target\":\"http://localhost:3000\",\"isStaticTarget\":false}}];
        fabric|OVERRIDE_API_SCHEMA|HTTPS|ADD
        fabric|OVERRIDE_API_PORT|443|ADD
        fabric|MAX_RETRIES_VALIDATE_SYSTEM_DB_CONNECTION|30|ADD
        fabric|SERVER_AUTHENTICATOR|fabric
      #cp_files: ''
      #idp_cert: ''

  # Each key will be added as enviroment to the fabric container
  secretsList:
    - name: common-env-secrets
      data:
        CONFIG_UPDATE_FILE: '/opt/apps/fabric/config-secrets/config'
        #COPY_FILES: ''
        #IDP_CERT_PATH: ''
        #IDP_ROLE: ''
        #NODE_ID: 'space-tenant'
        #CLUSTER_ID: 'space-tenant'
        PROJECT_NAME: 'test'
        SPACE_NAME: 'space-tenant'
    - name: cassandra-secrets
      data:
        cassandra.default.user: "cassandra"
        cassandra.default.password: "cassandra"
        cassandra.default.hosts: "cassandra-service"
  
  initSecretsList:
  - name: config-init-secrets
    data:
      #IDP_CERT_PATH: ''
      #IDP_ROLE: ''
      #GIT_BRANCH: 'main'
      #GIT_PATH_IN_REPO: ''
      #GIT_REPO: ''
      #GIT_TOKEN: ''
      START_FABRIC: 'false'
