name: k2v-ingress
services:
  socat:
    container_name: socat
    image: alpine/socat
    restart: always
    networks:
      - fab-infra
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "socat /dev/null TCP4:localhost:2375 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 8

  traefik:
    container_name: traefik
    image: traefik:latest
    depends_on:
      socat:
        condition: service_healthy
    restart: always
    networks:
      - fab-net
      - fab-infra
    ports:
      - ${API_PORT}:8080
      - ${INGRESS_HTTP_PORT}:80
      - ${INGRESS_HTTPS_PORT}:443
    volumes:
      - ./ssl-certs/:/etc/certs/
      - ./tls-config.yaml:/etc/traefik/dynamic/tls-config.yaml
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/etc/traefik/dynamic/tls-config.yaml"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://socat:2375"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
    labels:
      - "k2v-ingress"

networks:
  fab-infra:
    driver: bridge
    ipam:
      config:
        - subnet: "${INFRA_SUBNET}"
  fab-net:
    name: fab-net
    external: true
