apiVersion: v2
name: nginx-ingress-controller
description: An example Nginx ingress controller deployment for Kubernetes. This Helm chart demonstrates how to deploy and configure an Nginx ingress controller to manage HTTP and HTTPS traffic routing to services within the cluster. Configured as a reference implementation for the K2view site.
type: application
version: 1.3.8
appVersion: "1.12.1"
