{
 "title": "K2V K8S Monitor - Space Level",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "prometheus" },
   { "name": "cluster", "label": "Site", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{cluster=\"$cluster\", phase=\"Active\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\",namespace=\"$namespace\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - kube_pod_created{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - kube_pod_container_state_started{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_deployment_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - kube_deployment_created{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources Utilization by pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])*100/4)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Usage Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"$cluster\",namespace=\"$namespace\"} / kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources Allocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\",namespace=\"$namespace\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kube_ingress_path{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "kube_service_info{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_service_spec_type{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Policy Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "expr": "kube_networkpolicy_labels{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}