{
 "title": "tenant-namespace-level-healthawd",
 "description": "The Following Shows NameSpace Level Metrics/Logs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Site",
    "query": "eu-central-1-aws-dfaas-eks,eu-west3"
   },
   {
    "name": "namespace",
    "label": "Space",
    "query": {
     "query": "kube_namespace_labels{cluster=\"$cluster_name\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fabric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "fabric pods available ",
   "type": "stat",
   "description": "The total number of UP fabric nodes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_deployment_status_replicas_available{deployment=\"dev-fabric-deployment\", namespace=\"$namespace\", cluster=\"$cluster_name\"}\r\n)"
    }
   ]
  },
  {
   "title": "Avg Load Fabric per 1m",
   "type": "stat",
   "description": "Average Load Fabric Pods per 1m",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container!=\"\", pod=~\"dev-fabric-deployment.*\", cluster=\"$cluster_name\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fabric Pod RAM Usage",
   "type": "stat",
   "description": "Fabric Pods Current Ram Ussage",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"dev-fabric-deployment.*\", container!=\"\",cluster=\"$cluster_name\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"dev-fabric-deployment.*\",cluster=\"$cluster_name\"}) by (pod)) * 100\r\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Heap usage Fabric Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", namespace=\"$namespace\", cluster=\"$cluster_name\"} ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Read Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_k2view_fabric_stats_count{category=\"mdb\", stats=\"mdbFetchBytes\",namespace=\"$namespace\",cluster=\"$cluster_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_k2view_fabric_stats_count{category=\"mdb\",stats=\"mdbSaveBytes\",cluster=\"$cluster_name\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Fabric (max) 5min",
   "type": "stat",
   "description": "The number of max errors in fabric logs (count over 5 minutes)",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "{job=\"$namespace/dev-fabric\"}"
    }
   ]
  },
  {
   "title": "webserviceCalls AVG",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(avg by (key) (increase(com_k2view_fabric_stats_total{category=\"transactions\",stats=\"webserviceCalls\", namespace=\"$namespace\", cluster=\"$cluster_name\"}[5m])))/(avg by (key) (increase(com_k2view_fabric_stats_count{category=\"transactions\",stats=\"webserviceCalls\", namespace=\"$namespace\", cluster=\"$cluster_name\"}[5m])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"$namespace/dev-fabric\"}"
    }
   ]
  },
  {
   "title": "Cassandra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cass Pods avaliable",
   "type": "stat",
   "description": "The number of UP Cassandra Pods Avaliable",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_deployment_status_replicas_available{deployment=\"dev-cassandra-deployment\", namespace=\"$namespace\", cluster=\"$cluster_name\"}\r\n)"
    }
   ]
  },
  {
   "title": "Avg Load Cass per 1m",
   "type": "stat",
   "description": "Avg Load Cassandra per 1m",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container!=\"\", pod=~\"dev-cassandra-deployment.*\", cluster=\"$cluster_name\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cass Pod RAM Usage",
   "type": "stat",
   "description": "Cassandra Pods  RAM usage",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"dev-cassandra-deployment.*\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"dev-cassandra-deployment.*\"}) by (pod)) * 100\r\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Usage of Cassandra (TOP 5)",
   "type": "timeseries",
   "description": "Maximum Disk Usage of all the Cassandra Nodes",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, (100 - ((node_filesystem_avail_bytes{instance=~\".*:9100\",job=\"cassandra\",mountpoint=~\".*cassandra.*\", enviroment=\"prod\"} * 100)/  node_filesystem_size_bytes{instance=~\".*:9100\",job=\"cassandra\",mountpoint=~\".*cassandra.*\", enviroment=\"prod\"})))",
     "legendFormat": "{{node}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Pending Compactions Cassandra (TOP 5)",
   "type": "timeseries",
   "description": "The max pending compactions over all Cassandra nodes",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 20 },
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{instance=~\"10.237.*:7070\", enviroment=\"prod\"}",
     "legendFormat": " {{ip}}"
    }
   ]
  },
  {
   "title": "Errors Cassandra (max)",
   "type": "stat",
   "description": "The number of max errors in cassandra logs (count over 5 minutes)",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "{job=\"cassandra\"}"
    }
   ]
  }
 ]
}