apiVersion: v2
name: k2v-ingress
description: A Helm chart for K2view custom ingress controller's resources

type: application
version: 1.0.0
appVersion: "4.12.0"

dependencies:
  - name: ingress-nginx
    version: "~4"
    repository: "https://kubernetes.github.io/ingress-nginx/"
    condition: ingress-nginx.enabled
