apiVersion: v1
entries:
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.11.1
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.11.1
    created: "2024-08-06T19:55:05.58387904-05:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: a3ac88eafc1af1f9d1c83d657c7abba17f8b30f95fc6e381f8f6360a301dd9dc
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: puerco
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://raw.githubusercontent.com/k2view/blueprints/main/helm/k2v-ingress/charts/ingress-nginx-4.11.1.tgz
    version: 4.11.1
  k2v-ingress:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-08-06T19:55:05.575585696-05:00"
    dependencies:
    - condition: ingress-nginx.enabled
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx/
      version: ~4
    description: A Helm chart for K2view custom ingress controller's resources
    digest: b04bd3fa6ac1f6975736ffd774bafeaa3aa52b1f520573d18c68259b6336860b
    name: k2v-ingress
    type: application
    urls:
    - https://raw.githubusercontent.com/k2view/blueprints/main/helm/k2v-ingress/k2v-ingress-0.9.9.tgz
    version: 0.9.9
generated: "2024-08-06T19:55:05.566973281-05:00"
