{
 "title": "K2V K8S Monitor - Site Level",
 "tags": [
  "k2view",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "prometheus" },
   { "name": "cluster", "label": "Site", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(up{job=\"node-exporter\", cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Links", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 } },
  { "title": "Infra Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Nodes UP",
   "type": "stat",
   "gridPos": { "h": 9, "w": 1, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Load 5m",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 1, "y": 7 },
   "targets": [
    {
     "expr": "node_load5{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "table",
   "description": "Non available RAM memory",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{cluster=\"$cluster\"} * 100) / node_memory_MemTotal_bytes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{cluster=\"$cluster\", mountpoint=\"/\",fstype!=\"rootfs\"}) / (node_filesystem_size_bytes{cluster=\"$cluster\", mountpoint=\"/\",fstype!=\"rootfs\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count without(cpu, mode) (node_cpu_seconds_total{cluster=\"$cluster\", mode=\"idle\"}))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "description": "Total disk space available in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", mountpoint=\"/\",fstype!=\"rootfs\"} * 100)"
    }
   ]
  },
  { "title": "Infra by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$instance\",job=~\"node-exporter\"}) /  count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"node-exporter\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$instance\",job=~\"node-exporter\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "timeseries",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{instance=\"$instance\", mountpoint=\"/\",fstype!=\"rootfs\"}) / (node_filesystem_size_bytes{instance=\"$instance\", mountpoint=\"/\",fstype!=\"rootfs\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kube State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Cluster Pod Requested",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\"})/ sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory  Requested",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Total Namespaces Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\", cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\", cluster=\"$cluster\", namespace=~\".*-k2view\"})",
     "legendFormat": "K2view"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{cluster=\"$cluster\", namespace=~\".*-k2view\", deployment=~\".*fabric.*\"} > 0)",
     "legendFormat": "Active - k2view"
    }
   ]
  },
  {
   "title": "Pods per Namespace",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_phase{cluster=\"$cluster\", namespace=~\".*-k2view\", phase=\"Running\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_deployment_status_replicas_unavailable{cluster=\"$cluster\", namespace=~\".*-k2view\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Active namespaces and nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"})",
     "legendFormat": "Nodes"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{cluster=\"$cluster\", deployment=~\".*fabric.*\"} > 0)",
     "legendFormat": "Active namespaces"
    }
   ]
  },
  {
   "title": "Total namespaces with fabric",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_ready{cluster=\"$cluster\", deployment=~\".*fabric.*\"} > 0)",
     "legendFormat": "Fabric pods"
    }
   ]
  }
 ]
}