apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted-sa
  namespace: {{ .Values.namespace.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: no-permissions
  namespace: {{ .Values.namespace.name }}
rules: []  # No permissions granted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-no-permissions
  namespace: {{ .Values.namespace.name }}
subjects:
- kind: ServiceAccount
  name: restricted-sa
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: no-permissions
  apiGroup: rbac.authorization.k8s.io