{{- if .Values.tlsSecret.enabled }}
{{- if ne .Values.tlsSecret.keyPath "" }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: wildcard-certificate
  namespace: {{ .Values.namespace.name }}
data:
  tls.key: "{{- .Files.Get .Values.tlsSecret.keyPath | b64enc }}"
  tls.crt: "{{- .Files.Get .Values.tlsSecret.certPath | b64enc }}"
{{- end }}
{{- if ne .Values.tlsSecret.key "" }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: wildcard-certificate
  namespace: {{ .Values.namespace.name }}
data:
  tls.key: "{{ .Values.tlsSecret.key | b64enc }}"
  tls.crt: "{{ .Values.tlsSecret.cert | b64enc }}"
{{- end }}
{{- if ne .Values.tlsSecret.key_b64 "" }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: wildcard-certificate
  namespace: {{ .Values.namespace.name }}
data:
  tls.key: "{{ .Values.tlsSecret.key_b64 }}"
  tls.crt: "{{ .Values.tlsSecret.cert_b64 }}"
{{- end }}
{{- end }}