{{- if .Values.tlsSecret.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: wildcard-certificate
  namespace: {{ .Values.namespace.name }}
data:
  tls.key: "{{- .Files.Get .Values.tlsSecret.keyPath | b64enc }}"
  tls.crt: "{{- .Files.Get .Values.tlsSecret.crtPath | b64enc }}"
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-errors-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  {{- if .Values.tlsSecret.enabled }}
  tls:
  - hosts:
    - "*.{{ .Values.domain }}"
    secretName: wildcard-certificate
  {{- end }}
  rules:
  - host: "*.{{ .Values.domain }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-errors
            port:
              number: 80