apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: 404-config-secrets
  namespace: {{ .Values.namespace.name }}
data:
  K2_MANAGER_URL: {{ .Values.secrets.K2_MANAGER_URL | default "''" | b64enc }}
