{{ $namespace := default dict .Values.namespace }}
{{- $storage := default dict .Values.storage -}}
{{- $app_name := .Values.app_name | default .Chart.Name -}}
{{- /* ---------------------------- */ -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $app_name }}-claim
  namespace: {{ default .Release.Name $namespace.name }}
  labels:
    app: {{ $app_name }}
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if $storage.class }}
  storageClassName: {{ $storage.class }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "10Gi" $storage.allocated_amount }}