{{ $namespace := default dict .Values.namespace }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.app_name }}-secrets
  namespace: {{ default .Release.Name $namespace.name }}
data:
  {{- range .Values.secrets }}
  {{ .key }}: {{ .value | b64enc | quote }}
  {{- end }}
