# Default values for ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##    GCP
## - nginx-ingress-controller

gcp-nginx-ingress-controller:

  # Parent Domain - example google.com...
  domainName: "kdev-cluster-gcp.cloud-dev.k2view.com"

  # If the domain has a A lets Encrypt Certificate supply it here...
  tlsSecret:
    enabled: false
    keyPath: "additionals/privkey.pem"
    crtPath: "additionals/fullchain.pem"


  # CUSTOM ERRORS

  # Following is a flip switch to enable Custom Error pages in the Ingress Nginx Controller
  addErrorPage: true

  # Should deploy the test page of ingress?
  ingressTest:
    enabled: false


##    AWS

aws-nginx-ingress-controller:

  # AWS VPC cidr containing the K8s cluster
  vpcCIDR: "10.0.0.0/16"

  # ARN - to be associated with ingress-controller Route53 domain certificate
  awsDomainCert:

  # Top domain the would accomidate sub domains example - google.com 
  domainName:

  addErrorPage: false


##    CUSTOM ERRORS - nginx-ingress-controller-custom-errors

nginx-ingress-controller-custom-errors:

  namespace:
    create: false
    name: "ingress-nginx"

  # Parent Domain - example google.com...
  domain: "eu-west3-gcp.cloud.k2view.com"

  image: "europe-docker.pkg.dev/k2view-dfaas/k2view-share/nginx-error-page:latest"

  # The redirect to link to be set in the custom error
  secrets:
    K2_MANAGER_URL: "https://cloud.k2view.com"

  resource_allocation:
    requests:
      memory: 128Mi
      cpu: '0.1'
    limits:
      memory: 256Mi
      cpu: '0.4'

  tlsSecret:
    enabled: true
    keyPath: "additionals/privkey.pem"
    crtPath: "additionals/fullchain.pem"