# Default values for nginx-ingress-controller-custom-errors.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  create: false
  name: "ingress-nginx"

domain: "kdev-cluster-gcp.cloud-dev.k2view.com"

image: "europe-docker.pkg.dev/k2view-dfaas/k2view-share/nginx-error-page:latest"
#image: "docker.share.cloud.k2view.com/k2view/k2v-agent:latest"

# The redirect to link to be set in the custom error
secrets:
  K2_MANAGER_URL: "https://cloud.k2view.com"

resource_allocation:
  requests:
    memory: 128Mi
    cpu: '0.1'
  limits:
    memory: 256Mi
    cpu: '0.4'

  tlsSecret:
    enabled: true
    keyPath: "additionals/privkey.pem"
    crtPath: "additionals/fullchain.pem"